-- Snowflake CI/CD Lab Setup Script

-- Create roles
CREATE OR REPLACE ROLE CICD_LAB_ROLE;
GRANT ROLE CICD_LAB_ROLE TO ROLE SYSADMIN;
GRANT ROLE CICD_LAB_ROLE TO USER CURRENT_USER();

-- Grant necessary privileges 
GRANT CREATE DATABASE ON ACCOUNT TO ROLE CICD_LAB_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE CICD_LAB_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CICD_LAB_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE CICD_LAB_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CICD_LAB_ROLE;

-- Switch to CICD_LAB_ROLE
USE ROLE CICD_LAB_ROLE;

-- Create development and production databases
CREATE OR REPLACE DATABASE CICD_LAB_DEV;
CREATE OR REPLACE DATABASE CICD_LAB_PROD;

-- Create schemas
CREATE OR REPLACE SCHEMA CICD_LAB_DEV.DATA_SECURITY;
CREATE OR REPLACE SCHEMA CICD_LAB_PROD.DATA_SECURITY;

-- Create warehouse for the lab
CREATE OR REPLACE WAREHOUSE CICD_LAB_WH 
    WAREHOUSE_SIZE = XSMALL 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE;

-- Create stages for code deployment
CREATE OR REPLACE STAGE CICD_LAB_DEV.DATA_SECURITY.DEPLOYMENT;
CREATE OR REPLACE STAGE CICD_LAB_PROD.DATA_SECURITY.DEPLOYMENT;

-- Grant privileges
GRANT USAGE ON DATABASE CICD_LAB_DEV TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON DATABASE CICD_LAB_PROD TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON SCHEMA CICD_LAB_DEV.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON SCHEMA CICD_LAB_PROD.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON WAREHOUSE CICD_LAB_WH TO ROLE CICD_LAB_ROLE;
GRANT OPERATE ON WAREHOUSE CICD_LAB_WH TO ROLE CICD_LAB_ROLE;
GRANT CREATE FUNCTION ON SCHEMA CICD_LAB_DEV.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT CREATE FUNCTION ON SCHEMA CICD_LAB_PROD.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT CREATE TABLE ON SCHEMA CICD_LAB_DEV.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT CREATE TABLE ON SCHEMA CICD_LAB_PROD.DATA_SECURITY TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON STAGE CICD_LAB_DEV.DATA_SECURITY.DEPLOYMENT TO ROLE CICD_LAB_ROLE;
GRANT USAGE ON STAGE CICD_LAB_PROD.DATA_SECURITY.DEPLOYMENT TO ROLE CICD_LAB_ROLE;
